{{- range .Values.virtualServices }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "istio-resources.fullname" $ }}{{ end }}
  labels:
    {{- include "istio-resources.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml (omit . "name" "annotations" "labels") | nindent 2 }}
{{- end }}
