apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ required "gatewayClassName is required" .Values.gatewayClassName }}
  {{- with .Values.listeners }}
  listeners:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}