replicas: 1

# values that pertain to the unbound container, for more information
# on unbound configuration see http://unbound.net/documentation/unbound.conf.html
unbound:
  image:
    repository: alpinelinux/unbound
    tag: latest
    pullPolicy: IfNotPresent
  verbosity: 1
  numThreads: 1
  statsInterval: 0
  statsCumulative: "no"
  serverPort: 53

# values that pertain to the exechealthz container, for more information see
# https://github.com/kubernetes/contrib/tree/master/exec-healthz
healthz:
  image:
    repository: gcr.io/google-containers/exechealthz
    tag: "1.2"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # loadBalancerIP:
  # clusterIP:
  # externalIP:
  port: 53
  # Additional annotations (e.g. for cloud provider specific config)
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  externalTrafficPolicy: Cluster

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
# Controls which IP address ranges unbound will allow queries from.
# If you want to use unbound as an upstream for kube-dns, or allow other pods
# to query the resolver directly, you'll at least need to allow the
# clusterIpV4Cidr range.

# allowedIpRanges:
# - "10.10.10.10/20"

# You can set as many forward zones as needed by specifying the zone name
# and forward hosts. Forward hosts can be set by hostname or ip.

# forwardZones:
# - name: "fake.net"
#   forwardHosts:
#   - "fake1.host.net"
#   forwardIps:
#   - "10.10.10.10"

# Unbound can store DNS records in a "local zone." This facility can be used to
# assign context-specific names to a given IP address, and could also be used for
# private DNS if you don't want or have an external resolver.

# localRecords:
# - name: "fake3.host.net"
#   ip: "10.12.10.10"
