{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "generic-server.fullname" $) .name }}
  labels:
    {{- include "generic-server.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ default "http" .targetPort }}
      protocol: {{ default "tcp" .protocol }}
      name: {{ default "http" .name }}
    {{- end }}
  selector:
    {{- include "generic-server.selectorLabels" $ | nindent 4 }}
{{- end }}
