{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "..fullname" $) .name }}
  labels:
    {{- include "..labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ default "http" .targetPort }}
      protocol: {{ default "tcp" .protocol }}
      name: {{ default "http" .name }}
    {{- end }}
  selector:
    {{- include "..selectorLabels" $ | nindent 4 }}
{{- end }}
