# Default values for actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

repository: frauniki/helm-charts

labels: []

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 500Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  scaleDownDelaySecondsAfterScaleOut: 300
  totalNumberOfQueuedAndInProgressWorkflowRuns: true

env:
  #Key1: Value1
  #Key2: Value2

secretEnv:
  #Key3: Value3
