# Default values for envoy-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Provider configuration
provider: {}

# Bootstrap configuration
bootstrap: {}
# type: Replace
# value: |
#   admin:
#     access_log:
#     - name: envoy.access_loggers.file
#       typed_config:
#         "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
#         path: /dev/stdout

# Concurrency configuration
concurrency: 0

# ExtraArgs for Envoy
extraArgs: []
# - --log-level
# - debug

# Telemetry configuration
telemetry: {}

# Shutdown configuration
shutdown: {}
# drainTimeout: 30s
# minDrainDuration: 15s

# Additional annotations for EnvoyProxy
annotations: {}
