{{- if .Values.ec2NodeClass.create }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ include "karpenter-aws-provisoner.fullname" . }}
  labels:
    {{- include "karpenter-aws-provisoner.labels" . | nindent 4 }}
spec:
  {{- with .Values.ec2NodeClass }}
  amiFamily: {{ .amiFamily }}
  role: {{ .role }}
  {{- with .subnetSelectorTags }}
  subnetSelectorTerms:
    - tags: {{ . | toYaml | nindent 8 }}
  {{- end }}
  {{- with .securityGroupSelectorTags }}
  securityGroupSelectorTerms:
    - tags: {{ . | toYaml | nindent 8 }}
  {{- end }}
  {{- with .tags }}
  tags: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
