{{- range .Values.nodePools }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ include "karpenter-aws-provisoner.fullname" $ }}{{ if .name }}-{{ .name }}{{ end }}
  labels:
    {{- include "karpenter-aws-provisoner.labels" $ | nindent 4 }}
spec:
  {{- with .disruption }}
  disruption: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .limits }}
  limits: {{ . | toYaml | nindent 4 }}
  {{- end }}
  weight: {{ .weight }}
  template:
    spec:
      {{- if $.Values.ec2NodeClass.create }}
      nodeClassRef:
        name: {{ include "karpenter-aws-provisoner.fullname" $ }}
      {{- else }}
      nodeClassRef: {{ toYaml $.Values.ec2NodeClass | nindent 6 }}
      {{- end }}
      requirements: {{ .requirements | toYaml | nindent 6 }}
      {{- with .expireAfter }}
      expireAfter: {{ . }}
      {{- end }}
      {{- with .kubelet }}
      kubelet: {{ . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
