{{- range .Values.nodePools }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ include "karpenter-aws-provisoner.fullname" $ }}{{ if .name }}-{{ .name }}{{ end }}
  labels:
    {{- include "karpenter-aws-provisoner.labels" $ | nindent 4 }}
spec:
  {{- with .disruption }}
  disruption: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .limits }}
  limits: {{ . | toYaml | nindent 4 }}
  {{- end }}
  weight: {{ .weight }}
  template:
    spec:
      nodeClassRef:
        name: {{ include "karpenter-aws-provisoner.fullname" $ }}
      requirements: {{ .requirements | toYaml | nindent 6 }}
      {{- with .kubelet }}
      kubelet: {{ . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
