apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
