apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "gateway-class.fullname" . }}
  labels:
    {{- include "gateway-class.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  controllerName: {{ required "controllerName is required" .Values.controllerName }}
  {{- with .Values.description }}
  description: {{ . }}
  {{- end }}
  {{- with .Values.parametersRef }}
  parametersRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}