nameOverride: ""
fullnameOverride: ""

ec2NodeClass:
  create: true
  amiFamily: AL2
  role:
  subnetSelectorTags: {}
  securityGroupSelectorTags: {}
  tags: {}

nodePools:
  - name: ""
    requirements:
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]
    kubelet:
    weight: 0
    limits:
    disruption:
      expireAfter: 168h
      consolidationPolicy: WhenEmpty
      consolidateAfter: 30s
    nodeClassRef:
      name: ""
