apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-querier.fullname" . }}
  labels:
    {{- include "thanos-querier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10901
      targetPort: http
      protocol: TCP
      name: grpc
    - port: 10902
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thanos-querier.selectorLabels" . | nindent 4 }}
