apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlas-migration.configMapName" . }}
  annotations: {{ .Values.annotations | toYaml | nindent 4 }}
  labels: {{- include "atlas-migration.labels" . | nindent 4 }}
data: {{ .Values.schemas | toYaml | nindent 2 }}
