kind: Service
apiVersion: v1
metadata:
  name: {{ template "unbound.fullname" . }}
  labels:
    app: {{ template "unbound.name" . }}
    chart: {{ template "unbound.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.clusterIP }}
  clusterIP: {{ .Values.clusterIP }}
  {{- end }}
  {{- if .Values.externalIP }}
  externalIPs:
    - {{ .Values.externalIP }}
  {{- end }}
  selector:
    app: {{ template "unbound.name" . }}
    release: {{ .Release.Name }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
  - name: dns-udp
    protocol: UDP
    port: {{ .Values.unbound.serverPort }}
    targetPort: dns-udp
  - name: dns-tcp
    protocol: TCP
    port: {{ .Values.unbound.serverPort }}
    targetPort: dns-tcp
