{{- with .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "migration-job.fullname" $ }}-env
  labels:
    {{- include "migration-job.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
