{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-batch.fullname" $ }}-env
  labels:
    {{- include "generic-batch.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
