apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pluto.fullname" . }}
  labels:
    {{- include "pluto.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pluto.fullname" . }}
  labels:
    {{- include "pluto.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pluto.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "pluto.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
