apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pluto.fullname" . }}
  labels:
    {{- include "pluto.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.cronJob }}
  suspend: {{ .suspend }}
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "pluto.labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "pluto.serviceAccountName" . }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: [detect-all-in-cluster, -o, json]
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
